Repository Cadence-GitHub/Stouffville-By-laws-AI, pull requests merged in 2025-05, with the labels that each got.

#35 Enhance search queries with temporal references for improved bylaw retrieval
  backend/app/prompts.py
Labels: enhancement

#36 Implement complete bylaw processing pipeline with enhanced deduplication and status enrichment
  database/README.md
  database/init_chroma.py
  database/prepare_final_json.py
  database/prepare_json_bylaws_for_db.py
Labels: documentation, enhancement

#40 Add bylaw number search and fix keyword search functionality
  database/README.md
  database/search_bylaws.py
Labels: bug, enhancement

#42 Optimize bylaw retrieval with direct similarity search and active filtering
  README.md
  backend/README.md
  backend/app/chroma_retriever.py
Labels: enhancement

#43 Implemented auto-suggest functionality based on 150 questions.
  README.md
  backend/README.md
  backend/app.py
  backend/app/chroma_retriever.py
  backend/app/static/demo.css
  backend/app/static/demo.js
  database/AI-generated_Q&A.json
  database/README.md
  database/ingest_questions.py
Labels: enhancement

#45 Simplified bylaw viewer retrieval code and improved how bylaw number is displayed in the viewer
  backend/app/chroma_retriever.py
  backend/app/static/bylawViewer.js
Labels: enhancement

#49 Implement bylaw status filtering and optimize prompt system
  README.md
  backend/README.md
  backend/app.py
  backend/app/__init__.py
  backend/app/chroma_retriever.py
  backend/app/gemini_handler.py
  backend/app/prompts.py
  backend/app/static/demo.css
  backend/app/static/demo.js
  backend/app/templates/demo.html
  backend/app/token_counter.py
  database/README.md
Labels: enhancement

#50 Implement Inactive Bylaw Handling with Specialized Prompts
  README.md
  backend/README.md
  backend/app.py
  backend/app/__init__.py
  backend/app/chroma_retriever.py
  backend/app/gemini_handler.py
  backend/app/prompts.py
  backend/app/token_counter.py
  database/README.md
Labels: enhancement

#54 Implement a simple logging to a local text file, for starters
  README.md
  backend/README.md
  backend/app.py
  database/README.md
Labels: enhancement

#56 Voice recording support & HTTPS demo enhancement
  README.md
  backend/README.md
  backend/app.py
  backend/app/gemini_handler.py
  backend/app/prompts.py
  backend/app/static/demo.js
  backend/app/templates/demo.html
  backend/requirements.txt
Labels: enhancement

#61 Add Voice Query Recording Feature to Public Demo Interface
  README.md
  backend/README.md
  backend/app/static/images/microphone.png
  backend/app/static/public_demo.css
  backend/app/static/public_demo.html
  backend/app/static/public_demo.js
Labels: enhancement
